# Generated by Django 4.2.7 on 2026-05-17 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('objectives', models.TextField(verbose_name='Objetivos')),
                ('prerequisites', models.TextField(blank=True, verbose_name='Prerrequisitos')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('lesson_type', models.CharField(choices=[('theory', 'Teoría'), ('example', 'Ejemplo Resuelto'), ('demo', 'Demo Interactiva'), ('exam', 'Examen')], max_length=20, verbose_name='Tipo')),
                ('order', models.IntegerField(verbose_name='Orden')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('demo_app', models.CharField(blank=True, choices=[('regression', 'Regresión Lineal'), ('genetic', 'Algoritmo Genético')], max_length=50, verbose_name='App de demo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course')),
            ],
            options={
                'verbose_name': 'Lección',
                'verbose_name_plural': 'Lecciones',
                'ordering': ['order'],
                'unique_together': {('course', 'order')},
            },
        ),
    ]
