# Generated by Django 4.2.7 on 2026-05-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_lesson_demo_app_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration_months',
            field=models.IntegerField(default=6, verbose_name='Duración (meses)'),
        ),
    ]
