# Generated by Django 4.2.7 on 2026-05-17 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('passing_score', models.IntegerField(default=70, verbose_name='Puntaje mínimo')),
                ('questions_count', models.IntegerField(default=10, verbose_name='Número de preguntas')),
                ('time_limit_minutes', models.IntegerField(default=30, verbose_name='Límite de tiempo (minutos)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='courses.course')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Exámenes',
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Pregunta')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Opción Múltiple'), ('true_false', 'Verdadero/Falso')], max_length=20, verbose_name='Tipo')),
                ('options', models.JSONField(help_text='Para opción múltiple, lista de opciones', verbose_name='Opciones')),
                ('correct_answer', models.CharField(max_length=500, verbose_name='Respuesta correcta')),
                ('explanation', models.TextField(blank=True, verbose_name='Explicación')),
                ('difficulty', models.IntegerField(choices=[(1, 'Fácil'), (2, 'Media'), (3, 'Difícil')], default=1, verbose_name='Dificultad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.course')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Banco de Preguntas',
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.JSONField(help_text='Lista de IDs de preguntas', verbose_name='Preguntas')),
                ('user_answers', models.JSONField(default=dict, verbose_name='Respuestas del usuario')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Puntuación')),
                ('passed', models.BooleanField(default=False, verbose_name='Aprobado')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intento de Examen',
                'verbose_name_plural': 'Intentos de Exámenes',
                'ordering': ['-started_at'],
            },
        ),
    ]
